-- Mart layer: daily returns + a rolling feature table for the forecasting
-- baseline in python/forecast_baseline.py.

CREATE SCHEMA IF NOT EXISTS MARKET_DW.MARTS;

CREATE OR REPLACE TABLE MARKET_DW.MARTS.DAILY_RETURNS AS
SELECT
    TICKER,
    DATE,
    ADJ_CLOSE,
    LAG(ADJ_CLOSE) OVER (PARTITION BY TICKER ORDER BY DATE) AS PREV_ADJ_CLOSE,
    (ADJ_CLOSE / NULLIF(LAG(ADJ_CLOSE) OVER (PARTITION BY TICKER ORDER BY DATE), 0)) - 1
        AS DAILY_RETURN
FROM MARKET_DW.STAGING.STG_PRICES;

CREATE OR REPLACE TABLE MARKET_DW.MARTS.FEATURES_ROLLING AS
SELECT
    TICKER,
    DATE,
    DAILY_RETURN,
    AVG(DAILY_RETURN) OVER (
        PARTITION BY TICKER ORDER BY DATE
        ROWS BETWEEN 20 PRECEDING AND CURRENT ROW
    ) AS ROLLING_20D_AVG_RETURN,
    STDDEV(DAILY_RETURN) OVER (
        PARTITION BY TICKER ORDER BY DATE
        ROWS BETWEEN 20 PRECEDING AND CURRENT ROW
    ) AS ROLLING_20D_VOLATILITY
FROM MARKET_DW.MARTS.DAILY_RETURNS
WHERE DAILY_RETURN IS NOT NULL;
