-- RBAC design example -- illustrates the intended role layout for this
-- warehouse. This is a design-intent example (written against Snowflake's
-- documented GRANT syntax) and has NOT been executed against a live
-- account as part of this repo -- review before running in a real account.

CREATE ROLE IF NOT EXISTS MARKET_DW_LOADER;   -- COPY INTO / ingestion jobs
CREATE ROLE IF NOT EXISTS MARKET_DW_ANALYST;  -- read-only on marts
CREATE ROLE IF NOT EXISTS MARKET_DW_ADMIN;    -- schema/DDL owner

GRANT USAGE ON DATABASE MARKET_DW TO ROLE MARKET_DW_LOADER;
GRANT USAGE ON SCHEMA MARKET_DW.RAW TO ROLE MARKET_DW_LOADER;
GRANT INSERT, SELECT ON TABLE MARKET_DW.RAW.PRICES TO ROLE MARKET_DW_LOADER;

GRANT USAGE ON DATABASE MARKET_DW TO ROLE MARKET_DW_ANALYST;
GRANT USAGE ON SCHEMA MARKET_DW.MARTS TO ROLE MARKET_DW_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA MARKET_DW.MARTS TO ROLE MARKET_DW_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MARKET_DW.MARTS TO ROLE MARKET_DW_ANALYST;

GRANT OWNERSHIP ON DATABASE MARKET_DW TO ROLE MARKET_DW_ADMIN;

GRANT ROLE MARKET_DW_LOADER TO ROLE SYSADMIN;
GRANT ROLE MARKET_DW_ANALYST TO ROLE SYSADMIN;
GRANT ROLE MARKET_DW_ADMIN TO ROLE SYSADMIN;
